{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ui-kit",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.2.3.aar",
          "url": "android-ui-kit-0.2.3.aar",
          "size": 1701644,
          "sha512": "b372eda3481a919487ba276f2eec2de2e54dc7bad705585440df71cf8c2ee9152764da9cc2d2946e4fe374c8394f60d44595928baba643c858a9d9e56fb5895e",
          "sha256": "d15cac1749b79855e521b686ca6f22331390cd0b5624654487495229426705e5",
          "sha1": "06f4b00333b040678fda9f3c553f69ba16cb29b7",
          "md5": "82b4d02316a040197aa9ec63c875f7c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.2.3.aar",
          "url": "android-ui-kit-0.2.3.aar",
          "size": 1701644,
          "sha512": "b372eda3481a919487ba276f2eec2de2e54dc7bad705585440df71cf8c2ee9152764da9cc2d2946e4fe374c8394f60d44595928baba643c858a9d9e56fb5895e",
          "sha256": "d15cac1749b79855e521b686ca6f22331390cd0b5624654487495229426705e5",
          "sha1": "06f4b00333b040678fda9f3c553f69ba16cb29b7",
          "md5": "82b4d02316a040197aa9ec63c875f7c9"
        }
      ]
    }
  ]
}
