{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ui-kit",
    "version": "0.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-ai",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.10.0.aar",
          "url": "android-ui-kit-0.10.0.aar",
          "size": 2144244,
          "sha512": "a249b8e733d379942fd2fc0cce211bb268f50abc6ed52a12ae95c419b37d8e4dddcc59d41dfe5da21227ff1d6040a5aa30cb59e0d9ab7dfece070312853ba855",
          "sha256": "b60664e871a1600113aa9759e6ae013a749ba3d55e0f7934bce907813d0a1280",
          "sha1": "e6452cff79cd1a325b3f070b3afad2a14cede2ed",
          "md5": "d82dcc46e25bf9939d43df235ffcaf50"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-ai",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.10.0.aar",
          "url": "android-ui-kit-0.10.0.aar",
          "size": 2144244,
          "sha512": "a249b8e733d379942fd2fc0cce211bb268f50abc6ed52a12ae95c419b37d8e4dddcc59d41dfe5da21227ff1d6040a5aa30cb59e0d9ab7dfece070312853ba855",
          "sha256": "b60664e871a1600113aa9759e6ae013a749ba3d55e0f7934bce907813d0a1280",
          "sha1": "e6452cff79cd1a325b3f070b3afad2a14cede2ed",
          "md5": "d82dcc46e25bf9939d43df235ffcaf50"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "android-ui-kit-0.10.0-sources.jar",
          "url": "android-ui-kit-0.10.0-sources.jar",
          "size": 702421,
          "sha512": "cf2aa8fb844419a2d4615ccf8f9d840804627bd40e7de0cd0a1e216d4b8b1eb2ae9dbc9783bc22417fc036fdb9db433e1dd11facd341ffe14009d49f97803399",
          "sha256": "6202722f36bccb9ec85dc274e3917fb58c210dbec046423f5ae858945fe49e80",
          "sha1": "61a273829fc864873f1cd24e101c66c6c69c5156",
          "md5": "85d134e23c74efbb7c984c677d5e84aa"
        }
      ]
    }
  ]
}
