{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ui-kit",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.1.1.aar",
          "url": "android-ui-kit-0.1.1.aar",
          "size": 1506289,
          "sha512": "e6b9579051b909396fb5610fde93137248900cb78838d16e6ec5f48a1f0f535c863cc2fcb8996f4f27bee113b9d433053cf66c1f16bd43ddcd7f20cbe3eb537f",
          "sha256": "88a97538d20a254174ab85961bb071e86540a8632e37293c0f780dff1e239ccc",
          "sha1": "36200c2a48bf95a69582a579bde8709538fe9ba7",
          "md5": "8006bece26b8033904cc54d179f55c8a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.1.1.aar",
          "url": "android-ui-kit-0.1.1.aar",
          "size": 1506289,
          "sha512": "e6b9579051b909396fb5610fde93137248900cb78838d16e6ec5f48a1f0f535c863cc2fcb8996f4f27bee113b9d433053cf66c1f16bd43ddcd7f20cbe3eb537f",
          "sha256": "88a97538d20a254174ab85961bb071e86540a8632e37293c0f780dff1e239ccc",
          "sha1": "36200c2a48bf95a69582a579bde8709538fe9ba7",
          "md5": "8006bece26b8033904cc54d179f55c8a"
        }
      ]
    }
  ]
}
