{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ui-kit",
    "version": "0.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.2.4.aar",
          "url": "android-ui-kit-0.2.4.aar",
          "size": 1749024,
          "sha512": "505ce9abc0fceebbb7d5b0ecf73c275f5e73cc429088f86dad4d4782f9fbbb60c1cb523d612b275088ff0e4229d4abcde32b8a8712ec0cdd36a41385274cc273",
          "sha256": "c00a475239247b031048d10ed7a33f6cdbaa702540dbad2670e48f3cd6d67556",
          "sha1": "48cc02316a7707f4d03fd3b8b92d8bb0d44a5a14",
          "md5": "725459c5b63e9b4746eb2e2313fa75a8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.2.4.aar",
          "url": "android-ui-kit-0.2.4.aar",
          "size": 1749024,
          "sha512": "505ce9abc0fceebbb7d5b0ecf73c275f5e73cc429088f86dad4d4782f9fbbb60c1cb523d612b275088ff0e4229d4abcde32b8a8712ec0cdd36a41385274cc273",
          "sha256": "c00a475239247b031048d10ed7a33f6cdbaa702540dbad2670e48f3cd6d67556",
          "sha1": "48cc02316a7707f4d03fd3b8b92d8bb0d44a5a14",
          "md5": "725459c5b63e9b4746eb2e2313fa75a8"
        }
      ]
    }
  ]
}
