{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ui-kit",
    "version": "0.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.9.0.aar",
          "url": "android-ui-kit-0.9.0.aar",
          "size": 2097384,
          "sha512": "7c4c207d7c942464433454204885a752bd78100ec52ff13a5471478150857bd3febb232f710fed209a74b71ff052adb3fc7096858903f1441d16cb6272d7f702",
          "sha256": "6403cfd533bddb5bd2132a6944d5487f1df8dfaf3819946cdd63ec70bf19c39f",
          "sha1": "0c67ba006c531fadad48e27201ce25b96a320ec9",
          "md5": "50907b612cfd8ea8e4d8692f3cf2e24d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.9.0.aar",
          "url": "android-ui-kit-0.9.0.aar",
          "size": 2097384,
          "sha512": "7c4c207d7c942464433454204885a752bd78100ec52ff13a5471478150857bd3febb232f710fed209a74b71ff052adb3fc7096858903f1441d16cb6272d7f702",
          "sha256": "6403cfd533bddb5bd2132a6944d5487f1df8dfaf3819946cdd63ec70bf19c39f",
          "sha1": "0c67ba006c531fadad48e27201ce25b96a320ec9",
          "md5": "50907b612cfd8ea8e4d8692f3cf2e24d"
        }
      ]
    }
  ]
}
