{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ui-kit",
    "version": "0.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-ai",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.10.1.aar",
          "url": "android-ui-kit-0.10.1.aar",
          "size": 2146009,
          "sha512": "cb21f8b6f42f662da764df2d5251a335a181d8d9d7953b31d65699af19e7c6ffbf8482b35462804e0664f595041067e5eaf62b130ad110392ff31a0bbb3f0f21",
          "sha256": "4c66294906a5329220536f82711020f261c68b327297d476cc303d127a534c13",
          "sha1": "cb78210ade75d8cddd03c1e3f64d9e5f028f9119",
          "md5": "78e35172b16b3d504326fc9c5457aaff"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-ai",
          "version": {
            "requires": "4.2.2"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.10.1.aar",
          "url": "android-ui-kit-0.10.1.aar",
          "size": 2146009,
          "sha512": "cb21f8b6f42f662da764df2d5251a335a181d8d9d7953b31d65699af19e7c6ffbf8482b35462804e0664f595041067e5eaf62b130ad110392ff31a0bbb3f0f21",
          "sha256": "4c66294906a5329220536f82711020f261c68b327297d476cc303d127a534c13",
          "sha1": "cb78210ade75d8cddd03c1e3f64d9e5f028f9119",
          "md5": "78e35172b16b3d504326fc9c5457aaff"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "android-ui-kit-0.10.1-sources.jar",
          "url": "android-ui-kit-0.10.1-sources.jar",
          "size": 704121,
          "sha512": "f9a0861099abb973f891f255a38cccf3138f48ff7fbba69942300bcb897a82c620bad79680f7c1cf891d9433490ed880588245a1bbc40f4ec89215d58df09fe8",
          "sha256": "8ddcdc453f950f30c45f940a6d724e2d72ae64b2ba93054a932f74221467d002",
          "sha1": "ea7c72c1b55a985589c8277b3c405e0bf978395a",
          "md5": "4431af839a0063beb250e0420823e933"
        }
      ]
    }
  ]
}
