{
  "formatVersion": "1.1",
  "component": {
    "group": "com.quickblox",
    "module": "android-ui-kit",
    "version": "0.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.5.0.aar",
          "url": "android-ui-kit-0.5.0.aar",
          "size": 1797684,
          "sha512": "b945bed62499a89dd63e22425cbba58d4d818e3059c6be7b491d1a4b7de34e6d5baf2bd0237eda9d9b0463c0d6d530a9b3344eff29fcd761c39984fbe6bf1e8a",
          "sha256": "c798d826aab507aec484e58db2eb381890d2cb799c0e81588753618e2be0a9f0",
          "sha1": "1740a3005cc8f51b189f0b1910cef764d9fe1c38",
          "md5": "692401f88d3959f676234f16763be338"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.5.6"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "android.arch.lifecycle",
          "module": "extensions",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-messages",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-chat",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "quickblox-android-sdk-content",
          "version": {
            "requires": "4.1.1"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-answer-assistant",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-translate",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.quickblox",
          "module": "android-ai-editing-assistant",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "android-ui-kit-0.5.0.aar",
          "url": "android-ui-kit-0.5.0.aar",
          "size": 1797684,
          "sha512": "b945bed62499a89dd63e22425cbba58d4d818e3059c6be7b491d1a4b7de34e6d5baf2bd0237eda9d9b0463c0d6d530a9b3344eff29fcd761c39984fbe6bf1e8a",
          "sha256": "c798d826aab507aec484e58db2eb381890d2cb799c0e81588753618e2be0a9f0",
          "sha1": "1740a3005cc8f51b189f0b1910cef764d9fe1c38",
          "md5": "692401f88d3959f676234f16763be338"
        }
      ]
    }
  ]
}
